### ISSUE TITLE
Transfer to posthtml org

### ISSUE THREAD

**Issue by Scrum** [posthtml/posthtml-prism#1]
you need to make me an ‘owner’ of this package so that I can move it to posthtml org

**Comment by cossssmin** [comment]
Sent you a transfer request 👍

**Comment by Scrum** [comment]
> Oops! That repository transfer has expired. 

Oh sorry, I didn’t have time a bit) Let's try again

**Comment by cossssmin** [comment]
No problem, re-initiated the transfer 🙂

**Comment by Scrum** [comment]
Check permissions please

**Comment by cossssmin** [comment]
Looking good!
